### ISSUE TITLE
Typo in readme for import path for index.css

### ISSUE THREAD

**Issue by sags95** [IOfate/react-coinbase-commerce#1]
In the readme the import for the `index.css` file is incorrect, it should be `import '@iofate/react-coinbase-commerce/dist/esm/index.css'` instead of `import '@iofate/react-coinbase-commerce/esm/index.css';`

**Comment by Johann-S** [comment]
Hi @sags95 👋 

Thanks for the report! You're right, do not hesitate to create a PR to fix that 😉

**Comment by ianmiller347** [comment]
it really took that long to fix it and no PR was ever made? well here is the fix: https://github.com/IOfate/react-coinbase-commerce/pull/6
